# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LilVoters
email: contact@lilvoters.com
description: > # this means to ignore newlines until "baseurl:"
   Lil Voters is a collection of letters from children to elected officials reminding them that the decisions we make today will be inherited by them tomorrow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lilvoters.com" # the base hostname & protocol for your site
github_username:  foxmichellem

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"
